### ISSUE TITLE
无法支持scrollview

### ISSUE THREAD

**Issue by susuzero** [woxingxiao/PullToRefreshAndLoadMore#3]
你好，该项目无法支持scrollview，单纯实现pullable接口貌似无法正常使用
另外，PullLinearLayout，垂直方向，内容过长也无法正常使用，出现滑动冲突

**Comment by woxingxiao** [comment]
ScrollView的支持见[这里](https://github.com/jingchenUSTC/PullToRefreshAndLoad/blob/master/src/com/jingchen/pulltorefresh/pullableview/PullableScrollView.java)。 
LinearLayout本身是无法滚动的控件，所以如果你的内容太长超过一屏幕，建议换其它控件。
